Master
TachibanaLabs/imgbrd pull request #4
Opened 2018-01-31 00:46 UTC by Merak1

Ya me revolvió otra vez en git

2018-01-31 01:06 UTC, Merak1 commented
ᕙ(⇀‸↼‶)ᕗ

2018-01-31 18:49 UTC, neftalyluis requested changes

2018-01-31 18:49 UTC, neftalyluis commented on index.html
> +	firebase.database().ref('chat')
Indenta pls

2018-01-31 18:49 UTC, neftalyluis commented on index.html
> +	  var txtnombre = document.getElementById('nombre');
Me hace un poco de ruido que los selectores los tengas aquí, pregunta tonta de JS, si funciona con ese scope?

2018-01-31 18:55 UTC, Merak1 commented on index.html
> +	  var txtnombre = document.getElementById('nombre');
Pues según yo si, ya que inmediatamente llamas las variables en la función siguiente pero si quieres los cambio a const

2018-02-01 02:30 UTC, neftalyluis commented on index.html
> +	  var txtnombre = document.getElementById('nombre');
Ok, dejalo a ver que tal se ven 👍

2018-02-01 02:31 UTC, neftalyluis commented on index.html
> +	firebase.database().ref('chat')
Pues no mucho con el html, sino que se pueda leer facil y uno no tenga que indagar a donde le pertenece esta funcion

2018-02-02 01:46 UTC, Merak1 commented
test

2018-02-02 01:50 UTC, neftalyluis approved these changes

2018-02-02 01:51 UTC, merged