Master
TachibanaLabs/imgbrd pull request #6
Opened 2018-02-13 17:56 UTC by Merak1

cuarto intento

2018-02-13 18:05 UTC, neftalyluis requested changes

2018-02-13 18:05 UTC, neftalyluis commented on css/style2.css
> +/*#serval-test{
Si no sirven, quitalos

2018-02-13 18:05 UTC, neftalyluis commented on index.html
> +	var hulabula =Math.random().toString(36).substr(2, 5);
no me dice nada el nombre de esta variable, renombra

2018-02-13 18:05 UTC, neftalyluis commented on index.html
> +	document.getElementById("hulabula").innerHTML = Math.random().toString(36).substr(2, 5);
indenta

2018-02-13 18:05 UTC, neftalyluis commented on index.html
> +
quita saltos de linea, hazlo legible

2018-02-13 18:05 UTC, neftalyluis commented on index.html
> +	<!-- <script src="js/ js.js"></script> -->
quitalo si no se va a usar

2018-02-13 18:05 UTC, neftalyluis commented on index.html
> +<!-- _______________________________________________________________ -->
?

2018-02-13 18:05 UTC, neftalyluis commented on index.html
> +															<button onclick="blanco()" type="button" id="btnEnviar">Enviar</button>
dale legibilidad

2018-02-13 18:05 UTC, neftalyluis commented on css/style.css
>  ul{
porque dos css?, uno solamente

2018-02-13 18:05 UTC, neftalyluis commented on container.html
> +<!DOCTYPE html>
para que es este hmtl?

2018-02-13 18:16 UTC, Merak1 commented on container.html
> +<!DOCTYPE html>
Este lo estaba ocupando de prueba y se me olvidó eliminar, se va.

2018-02-13 18:23 UTC, Merak1 commented
Lo que quería que vieras más que nada era el funcionamiento, y como me trabo a la hora de implementar la funcion de enviar a firebase y la función para eliminar el contenido de los input y el textarea

2018-02-13 18:26 UTC, neftalyluis commented
Cuando quieras que cheque esas cosas indicalo en el pr

El 13 feb. 2018 12:23 PM, "Merak1" <notifications@github.com> escribió:

> Lo que quería que vieras más que nada era el funcionamiento, y como me
> trabo a la hora de implementar la funcion de enviar a firebase y la función
> para eliminar el contenido de los input y el textarea
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/TachibanaLabs/imgbrd/pull/6#issuecomment-365357599>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGVmiJ4mnX9_O-nW1TmXxNgxYRMgdhThks5tUdMigaJpZM4SEKG8>
> .
>

2018-02-13 18:41 UTC, Merak1 commented
lo decía por que no he conseguido dejar los inputs en blanco sin inerferir con la función de firebase

2018-02-13 21:58 UTC, Merak1 commented on index.html
> +	<!-- <script src="js/ js.js"></script> -->
✔

2018-02-14 19:33 UTC, Merak1 commented on index.html
> +
✔

2018-02-14 19:33 UTC, Merak1 commented on css/style2.css
> +/*#serval-test{
✔

2018-02-14 19:43 UTC, neftalyluis commented on index.html
> +
Cuando haces push y está un cambio en esa línea se hace como un check en automático 🤔, nomás digo

2018-02-14 19:45 UTC, Merak1 commented on index.html
> +
Los estoy poniendo para ir haciendo las cosas una a una

2018-02-14 19:46 UTC, Merak1 commented on index.html
> +
Y no hacerme bolas que ayer no pude avanzar mucho

2018-02-14 19:46 UTC, Merak1 commented on index.html
> +
Por cierto, cuando voy a tu casa para lo del teclado?

Para comprarlo antes, eso si priero me tienen que pagar

2018-02-14 19:57 UTC, Merak1 commented on index.html
> +	var hulabula =Math.random().toString(36).substr(2, 5);
✔

2018-02-14 19:58 UTC, Merak1 commented on index.html
> +															<button onclick="blanco()" type="button" id="btnEnviar">Enviar</button>
✔

2018-02-16 00:22 UTC, neftalyluis commented on index.html
> +
cuando puedas

2018-02-16 00:23 UTC, Merak1 commented on index.html
> +
tu cuando puedas, yo soy el que no tiene trabajo.
Voy a lanzar otro pr para que veas los cambios

2018-02-16 00:25 UTC, neftalyluis commented
Mmmmm, no creo que sea necesario, solo hazle push a master desde tu repo
para que se reflejen los cambios

El 15 feb. 2018 6:23 PM, "Merak1" <notifications@github.com> escribió:

> *@Merak1* commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/TachibanaLabs/imgbrd/pull/6#discussion_r168648653>:
>
> >  		});
>  		chatUl.innerHTML = html;
>  	});
> +	function hulabula(){
> +	document.getElementById("hulabula").innerHTML = Math.random().toString(36).substr(2, 5);
> +	}
> +
> +
> +	document.getElementById("chat").addEventListener("click", blanco);
> +	function blanco(){
> +		document.getElementById("form").reset();
> +		
> +
>
> tu cuando puedas, yo soy el que no tiene trabajo.
> Voy a lanzar otro pr para que veas los cambios
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/TachibanaLabs/imgbrd/pull/6#discussion_r168648653>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGVmiLNZMlCN8JJRERdcEbXGjFnQctLWks5tVMqegaJpZM4SEKG8>
> .
>

2018-02-16 00:40 UTC, Merak1 commented
a ver revisa si ya

2018-02-16 00:43 UTC, neftalyluis commented
Nope, no veo ningun commit nuevo

2018-02-16 00:46 UTC, neftalyluis commented
Ya estuvo, deja checo tu codigo

2018-02-16 00:58 UTC, neftalyluis requested changes

2018-02-16 00:58 UTC, neftalyluis commented on index.html
> +	  var randomId =Math.random().toString(36).substr(2, 5);
Formato pls!, voy a agregar un linter para que te ayude en eso en los proximos dias, pero por ahorita vas a tener que hacerlo a manita

2018-02-16 00:58 UTC, neftalyluis commented on index.html
> +	// ESTA ES LA PARTE QUE NO PUEDO SOLUCIONAR PUESTO QUE INTERFIERE CON LA FUNCION ANTERIOR 	PARA PODER DEJAR LOS INPUTS Y EL TEXT
Este reset al se lo puedes poner al final del evento `btnEnviar.addEventListener("click"`

2018-02-16 00:58 UTC, neftalyluis commented on js/js.js
> +
Porque tenemos dos veces el mismo codigo?

2018-02-16 00:58 UTC, neftalyluis commented on js/js.js
> +
Es copia exacta de lo que esta en el HTML, elige un lugar

2018-02-16 00:59 UTC, Merak1 commented on js/js.js
> +
no lo quité? 
Pta

2018-02-16 01:00 UTC, Merak1 commented on index.html
> +	  var randomId =Math.random().toString(36).substr(2, 5);
A que te refieres con formato?

2018-02-16 01:00 UTC, neftalyluis commented
Estas mejorando, pero necesito que te salgas de tu burbuja de perfeccionismo, pregunta si no sabes, y aprende a darte por vencido y preguntar

2018-02-16 01:03 UTC, neftalyluis commented on index.html
> +	  var randomId =Math.random().toString(36).substr(2, 5);
# No
`var randomId =Math.random().toString(36).substr(2, 5);`

# Si
`var randomId = Math.random().toString(36).substr(2, 5);`

2018-02-16 01:04 UTC, Merak1 commented on index.html
> +	  var randomId =Math.random().toString(36).substr(2, 5);
Ohh ok, no lo había visto.
Gotchu fam

2018-02-16 01:11 UTC, Merak1 commented on index.html
> +	// ESTA ES LA PARTE QUE NO PUEDO SOLUCIONAR PUESTO QUE INTERFIERE CON LA FUNCION ANTERIOR 	PARA PODER DEJAR LOS INPUTS Y EL TEXT
Se lo come antes de que se envie a firebase

2018-02-16 01:11 UTC, neftalyluis commented
Ponlo en el evento de Firebase entons

El 15 feb. 2018 7:11 PM, "Merak1" <notifications@github.com> escribió:

> *@Merak1* commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/TachibanaLabs/imgbrd/pull/6#discussion_r168655216>:
>
> >  	});
> +
> +
> +
> +	
> +	// document.getElementById("chat").addEventListener("click", blanco);
> +	// function blanco(){
> +	// 	document.getElementById("form").reset();
> +	// }
> +	// ESTA ES LA PARTE QUE NO PUEDO SOLUCIONAR PUESTO QUE INTERFIERE CON LA FUNCION ANTERIOR 	PARA PODER DEJAR LOS INPUTS Y EL TEXT
>
> Se lo come antes de que se envie a firebase
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/TachibanaLabs/imgbrd/pull/6#discussion_r168655216>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGVmiErpl8wDtg0WaTlmTYPe0dNXdgY_ks5tVNWygaJpZM4SEKG8>
> .
>

2018-02-16 01:17 UTC, Merak1 commented
![image](https://user-images.githubusercontent.com/19805451/36289262-b5520b08-1284-11e8-8a1e-13a49b5662ed.png)


´dentro de la función de snapshot se come todos los divs, cuando esta después del call de chatUl.innerHTML = html;
se envia a firebase pero sin nada en nombre y mensaje y solo se le genera su id

2018-02-16 01:18 UTC, neftalyluis commented
Corrige los detalles de estilo, hago merge y ya te digo que pasa

2018-02-16 01:19 UTC, Merak1 commented
Ok. de mientras la función la dejo entre comentada

2018-02-16 01:24 UTC, merged